"""created tables: text_template, message, correspondent, recipient, delivery

Revision ID: 7e442b2d139b
Revises: 
Create Date: 2025-09-12 18:06:42.472394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e442b2d139b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondent',
    sa.Column('correspondent_id', sa.UUID(), nullable=False),
    sa.Column('correspondent_channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEB', name='channel_enum', native_enum=False), nullable=False),
    sa.Column('correspondent_name', sa.String(), nullable=False),
    sa.Column('correspondent_from_address', sa.String(), nullable=True),
    sa.Column('correspondent_provider', sa.String(), nullable=False),
    sa.Column('correspondent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correspondent_is_active', sa.Boolean(), nullable=False),
    sa.Column('correspondent_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('correspondent_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('correspondent_id')
    )
    op.create_index(op.f('ix_correspondent_correspondent_channel'), 'correspondent', ['correspondent_channel'], unique=False)
    op.create_table('text_template',
    sa.Column('text_template_id', sa.UUID(), nullable=False),
    sa.Column('text_template_code', sa.String(), nullable=False),
    sa.Column('text_template_channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEB', name='channel_enum', native_enum=False), nullable=False),
    sa.Column('text_template_is_active', sa.Boolean(), nullable=False),
    sa.Column('text_template_subject', sa.String(), nullable=True),
    sa.Column('text_template_content', sa.String(), nullable=False),
    sa.Column('text_template_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_template_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_template_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('text_template_id')
    )
    op.create_index(op.f('ix_text_template_text_template_channel'), 'text_template', ['text_template_channel'], unique=False)
    op.create_index(op.f('ix_text_template_text_template_code'), 'text_template', ['text_template_code'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('text_template_id', sa.UUID(), nullable=True),
    sa.Column('correspondent_id', sa.UUID(), nullable=True),
    sa.Column('message_subject', sa.String(), nullable=True),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_status', sa.Enum('PENDING', 'SENDING', 'SENT', 'PARTIAL_FAILED', 'FAILED', name='message_status_enum', native_enum=False), nullable=False),
    sa.Column('message_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('message_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correspondent_id'], ['correspondent.correspondent_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_template_id'], ['text_template.text_template_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('recipient',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEB', name='channel_enum', native_enum=False), nullable=False),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('recipient_locale', sa.String(), nullable=True),
    sa.Column('recipient_timezone', sa.String(), nullable=True),
    sa.Column('recipient_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('delivery',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('delivery_attempt_no', sa.Integer(), nullable=False),
    sa.Column('delivery_provider', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', name='delivery_status_enum', native_enum=False), nullable=False),
    sa.Column('delivery_provider_message_id', sa.String(), nullable=True),
    sa.Column('delivery_error_code', sa.String(), nullable=True),
    sa.Column('delivery_error_message', sa.String(), nullable=True),
    sa.Column('delivery_queued_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.recipient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    op.drop_table('recipient')
    op.drop_table('message')
    op.drop_index(op.f('ix_text_template_text_template_code'), table_name='text_template')
    op.drop_index(op.f('ix_text_template_text_template_channel'), table_name='text_template')
    op.drop_table('text_template')
    op.drop_index(op.f('ix_correspondent_correspondent_channel'), table_name='correspondent')
    op.drop_table('correspondent')
    # ### end Alembic commands ###
