"""created tables: text_template, message, email_correspondent, telegram_correspondent, recipient, delivery

Revision ID: 98bef34d9473
Revises: 7a7984dea68a
Create Date: 2025-09-15 14:44:33.809481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98bef34d9473'
down_revision: Union[str, Sequence[str], None] = '7a7984dea68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_correspondent', sa.Column('email_correspondent_id', sa.UUID(), nullable=False))
    op.add_column('email_correspondent', sa.Column('email_correspondent_name', sa.String(), nullable=False))
    op.add_column('email_correspondent', sa.Column('email_correspondent_is_active', sa.Boolean(), nullable=False))
    op.add_column('email_correspondent', sa.Column('email_correspondent_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('email_correspondent', sa.Column('email_correspondent_update_at', sa.DateTime(), nullable=True))
    op.drop_column('email_correspondent', 'correspondent_name')
    op.drop_column('email_correspondent', 'correspondent_id')
    op.drop_column('email_correspondent', 'correspondent_create_at')
    op.drop_column('email_correspondent', 'correspondent_update_at')
    op.drop_column('email_correspondent', 'correspondent_is_active')
    op.add_column('telegram_correspondent', sa.Column('telegram_correspondent_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('telegram_correspondent', sa.Column('telegram_correspondent_update_at', sa.DateTime(), nullable=True))
    op.drop_column('telegram_correspondent', 'correspondent_create_at')
    op.drop_column('telegram_correspondent', 'correspondent_update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_correspondent', sa.Column('correspondent_update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('telegram_correspondent', sa.Column('correspondent_create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('telegram_correspondent', 'telegram_correspondent_update_at')
    op.drop_column('telegram_correspondent', 'telegram_correspondent_create_at')
    op.add_column('email_correspondent', sa.Column('correspondent_is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('email_correspondent', sa.Column('correspondent_update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_correspondent', sa.Column('correspondent_create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('email_correspondent', sa.Column('correspondent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('email_correspondent', sa.Column('correspondent_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('email_correspondent', 'email_correspondent_update_at')
    op.drop_column('email_correspondent', 'email_correspondent_create_at')
    op.drop_column('email_correspondent', 'email_correspondent_is_active')
    op.drop_column('email_correspondent', 'email_correspondent_name')
    op.drop_column('email_correspondent', 'email_correspondent_id')
    # ### end Alembic commands ###
