"""created tables: text_template, message, email_correspondent, telegram_correspondent, recipient, delivery

Revision ID: ce95669f8720
Revises: 
Create Date: 2025-09-16 20:26:31.539762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce95669f8720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_correspondent',
    sa.Column('email_correspondent_id', sa.UUID(), nullable=False),
    sa.Column('email_correspondent_name', sa.String(), nullable=False),
    sa.Column('email_correspondent_is_active', sa.Boolean(), nullable=False),
    sa.Column('email_host', sa.String(), nullable=False),
    sa.Column('email_port', sa.Integer(), nullable=False),
    sa.Column('email_sender', sa.String(), nullable=False),
    sa.Column('email_password', sa.String(), nullable=False),
    sa.Column('email_correspondent_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_correspondent_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email_correspondent_id')
    )
    op.create_table('recipient',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('recipient_locale', sa.String(), nullable=True),
    sa.Column('recipient_timezone', sa.String(), nullable=True),
    sa.Column('recipient_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('telegram_correspondent',
    sa.Column('telegram_correspondent_id', sa.UUID(), nullable=False),
    sa.Column('telegram_correspondent_name', sa.String(), nullable=False),
    sa.Column('telegram_correspondent_is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token', sa.String(), nullable=False),
    sa.Column('telegram_correspondent_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('telegram_correspondent_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_correspondent_id')
    )
    op.create_table('text_template',
    sa.Column('text_template_id', sa.UUID(), nullable=False),
    sa.Column('text_template_code', sa.String(), nullable=False),
    sa.Column('text_template_is_active', sa.Boolean(), nullable=False),
    sa.Column('text_template_subject', sa.String(), nullable=True),
    sa.Column('text_template_content', sa.String(), nullable=False),
    sa.Column('text_template_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_template_channel', sa.Enum('EMAIL', 'TELEGRAM', name='template_channel_enum', native_enum=False), nullable=False),
    sa.Column('text_template_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_template_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('text_template_id')
    )
    op.create_index(op.f('ix_text_template_text_template_code'), 'text_template', ['text_template_code'], unique=False)
    op.create_table('delivery',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('delivery_attempt_no', sa.Integer(), nullable=False),
    sa.Column('delivery_provider', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', name='delivery_status_enum', native_enum=False), nullable=False),
    sa.Column('delivery_provider_message_id', sa.String(), nullable=True),
    sa.Column('delivery_error_code', sa.String(), nullable=True),
    sa.Column('delivery_error_message', sa.String(), nullable=True),
    sa.Column('delivery_queued_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.recipient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('message_body', sa.String(), nullable=False),
    sa.Column('message_status', sa.Enum('PENDING', 'SENDING', 'SENT', 'PARTIAL_FAILED', 'FAILED', name='messagestatusenum'), nullable=False),
    sa.Column('message_channel', sa.Enum('EMAIL', 'TELEGRAM', name='channel_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.recipient_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_message_channel'), 'message', ['message_channel'], unique=False)
    op.create_index(op.f('ix_message_recipient_id'), 'message', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_recipient_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_channel'), table_name='message')
    op.drop_table('message')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_text_template_text_template_code'), table_name='text_template')
    op.drop_table('text_template')
    op.drop_table('telegram_correspondent')
    op.drop_table('recipient')
    op.drop_table('email_correspondent')
    # ### end Alembic commands ###
